### ISSUE TITLE
Protégé Desktop 5 Support

### ISSUE THREAD

**Issue by ddbd** [VisualDataWeb/ProtegeVOWL#2]
Add Support for Protégé Desktop 5

More Information:
Level:       ERROR
Time:        1459000248877
Message:     Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoSuchMethodError
StackTrace:  
    graphModifier.TransformOWLtoGraph.transformClasses(TransformOWLtoGraph.java:439)
    graphModifier.TransformOWLtoGraph.transformOWLtoGraph(TransformOWLtoGraph.java:47)
    protege.VOWLViewComponent.initialiseOWLView(VOWLViewComponent.java:75)
    org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:46)
    org.protege.editor.core.ui.view.View.createContent(View.java:424)
    org.protege.editor.core.ui.view.View.createUI(View.java:217)
    org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123)
    java.awt.Component.processHierarchyEvent(Component.java:6692)
    java.awt.Component.processEvent(Component.java:6311)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.Component.createHierarchyEvents(Component.java:5541)
    java.awt.Container.createHierarchyEvents(Container.java:1443)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Container.createHierarchyEvents(Container.java:1439)
    java.awt.Component.show(Component.java:1622)
    java.awt.Component.show(Component.java:1654)
    java.awt.Component.setVisible(Component.java:1606)
    javax.swing.JComponent.setVisible(JComponent.java:2644)
    javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394)
    javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
    javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
    javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
    javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
    javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
    javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
    java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
    java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
    java.awt.Component.processMouseEvent(Component.java:6522)
    javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    java.awt.Component.processEvent(Component.java:6290)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
    java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    java.awt.Container.dispatchEventImpl(Container.java:2278)
    java.awt.Window.dispatchEventImpl(Window.java:2750)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:702)
    java.awt.EventQueue$3.run(EventQueue.java:696)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.awt.EventQueue$4.run(EventQueue.java:724)
    java.awt.EventQueue$4.run(EventQueue.java:722)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jimmyangel** [comment]
# On a Mac OSX 10.11.5

2016-07-30 14:48:26.466 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLClass.getAnnotations(Lorg/semanticweb/owlapi/model/OWLOntology;)Ljava/util/Set;
    at graphModifier.TransformOWLtoGraph.transformClasses(TransformOWLtoGraph.java:439) ~[na:na]
    at graphModifier.TransformOWLtoGraph.transformOWLtoGraph(TransformOWLtoGraph.java:47) ~[na:na]
    at protege.VOWLViewComponent.initialiseOWLView(VOWLViewComponent.java:75) ~[na:na]
    at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:46) ~[na:na]
    at org.protege.editor.core.ui.view.View.createContent(View.java:424) ~[na:na]
    at org.protege.editor.core.ui.view.View.createUI(View.java:217) ~[na:na]
    at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123) ~[na:na]
    at java.awt.Component.processHierarchyEvent(Component.java:6692) ~[na:1.8.0_40]
    at java.awt.Component.processEvent(Component.java:6311) ~[na:1.8.0_40]
    at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
    at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
    at java.awt.Component.createHierarchyEvents(Component.java:5541) ~[na:1.8.0_40]
    at java.awt.Container.createHierarchyEvents(Container.java:1443) ~[na:1.8.0_40]
    at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
    at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
    at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
    at java.awt.Container.createHierarchyEvents(Container.java:1439) ~[na:1.8.0_40]
    at java.awt.Component.show(Component.java:1622) ~[na:1.8.0_40]
    at java.awt.Component.show(Component.java:1654) ~[na:1.8.0_40]
    at java.awt.Component.setVisible(Component.java:1606) ~[na:1.8.0_40]
    at javax.swing.JComponent.setVisible(JComponent.java:2644) ~[na:1.8.0_40]
    at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) ~[na:1.8.0_40]
    at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) ~[na:1.8.0_40]
    at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) ~[na:1.8.0_40]
    at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) ~[na:1.8.0_40]
    at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) ~[na:1.8.0_40]
    at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) ~[na:1.8.0_40]
    at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) ~[na:1.8.0_40]
    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) ~[na:1.8.0_40]
    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) ~[na:1.8.0_40]
    at java.awt.Component.processMouseEvent(Component.java:6522) ~[na:1.8.0_40]
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_40]
    at java.awt.Component.processEvent(Component.java:6290) ~[na:1.8.0_40]
    at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
    at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530) ~[na:1.8.0_40]
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) ~[na:1.8.0_40]
    at java.awt.Container.dispatchEventImpl(Container.java:2278) ~[na:1.8.0_40]
    at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_40]
    at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) ~[na:1.8.0_40]
    at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
    at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_40]
    at java.awt.EventQueue$4.run(EventQueue.java:724) ~[na:1.8.0_40]
    at java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:1.8.0_40]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) ~[na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]

**Comment by dbrans** [comment]
Bump.

**Comment by mans0954** [comment]
I've released a [build](https://github.com/mans0954/ProtegeVOWL/releases/tag/v0.1.0-alpha.1) which works with Protégé 5.1.

**Comment by steffen-l** [comment]
Great. Thanks, Christopher! I have merged your changes and uploaded the compiled JAR to http://vowl.visualdataweb.org/protegevowl.html (I removed some libs from the JAR that are not required, which reduces the file size significantly (less than 1MB now).
