### ISSUE TITLE
Error prevents tab working: Optional.get() cannot be called on an absent value

### ISSUE THREAD

**Issue by KDDS89** [VisualDataWeb/ProtegeVOWL#4]
After places the jar file in the Protege plug-ins folder and then opening Protege, I get the following message on the 'VOWL' tab.

An error occurred whilst creating the view
IllegalStateException:
Optional.get() cannot be called on an absent value

I am on Windows 10.

Here is the log file entry:
`2017-01-12 11:06:11.001 [AWT-EventQueue-0] ERROR View    An error occurred whilst creating the view content for the 'VOWL Viewer' view: {}
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47) ~[guava.jar:na]
	at graphModifier.TransformOWLtoGraph.transformClasses(TransformOWLtoGraph.java:473) ~[na:na]
	at graphModifier.TransformOWLtoGraph.transformOWLtoGraph(TransformOWLtoGraph.java:50) ~[na:na]
	at protege.VOWLViewComponent.initialiseOWLView(VOWLViewComponent.java:75) ~[na:na]
	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
	at org.protege.editor.core.ui.view.View.createContent(View.java:424) [protege-editor-core.jar:na]
	at org.protege.editor.core.ui.view.View.createUI(View.java:217) [protege-editor-core.jar:na]
	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123) [protege-editor-core.jar:na]
	at java.awt.Component.processHierarchyEvent(Component.java:6692) [na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6311) [na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
	at java.awt.Component.createHierarchyEvents(Component.java:5541) [na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1443) [na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
	at java.awt.Component.show(Component.java:1622) [na:1.8.0_40]
	at java.awt.Component.show(Component.java:1654) [na:1.8.0_40]
	at java.awt.Component.setVisible(Component.java:1606) [na:1.8.0_40]
	at javax.swing.JComponent.setVisible(JComponent.java:2644) [na:1.8.0_40]
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) [na:1.8.0_40]
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) [na:1.8.0_40]
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) [na:1.8.0_40]
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) [na:1.8.0_40]
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) [na:1.8.0_40]
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) [na:1.8.0_40]
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) [na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) [na:1.8.0_40]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) [na:1.8.0_40]
	at java.awt.Component.processMouseEvent(Component.java:6522) [na:1.8.0_40]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6290) [na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) [na:1.8.0_40]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530) [na:1.8.0_40]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) [na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2278) [na:1.8.0_40]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) [na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:724) [na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:722) [na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]`

**Comment by gooodguy** [comment]
Hi,
I came up with the same error. I solved this by adding an ontology element to my owl file:
```xml
<owl:Ontology rdf:about="">
</owl:Ontology>
```

**Comment by jmoflav** [comment]
I tried adding the element, which did not resolve the error described herein.  @KDDS89 Did you ever resolve or find another plugin that renders a satisfactory VOWL within Protege?

**Comment by ddbd** [comment]
@jmoflav @KDDS89 
Just noticed this is the same issue as the recently reported issue [#14](https://github.com/VisualDataWeb/ProtegeVOWL/issues/14).
You will find a updated version there.
